version: '3'
services:
    tiny_url:
        build: ./
        image: shahnishit/tiny_url:0.0.2
        container_name: tiny_url
        ports:
            - "5000:5000"
        depends_on:
            - mongo
        networks:
            - tinyurl

    mongo:
        image: mongo:latest
        container_name: mongodb
        ports:
          - "27017:27017"
        networks:
          - tinyurl

networks:
    tinyurl:
        driver: bridge
